---
apiVersion: v2
appVersion: 1.16.0
version: 0.1.0
name: template
description: A Helm chart for Kubernetes
type: application
homepage: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/"
icon: ""
dependencies:
  - name: common
    version: ~0.1.5
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - foo
  - bar
sources:
  - foo
  - https://hub.docker.com/r/linuxserver/
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
