---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "template.fullname" . }}
  labels:
  {{- include "template.labels" . | nindent 4 }}
type: Opaque
data:
  GOTIFY_DEFAULTUSER_NAME: {{ .Values.secret.user | b64enc | quote }}
  GOTIFY_DEFAULTUSER_PASS: {{ .Values.secret.pass | b64enc | quote }}
