
{{- if .Values.secret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "template.fullname" . }}
  labels:
  {{- include "template.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secret }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
